#!/usr/bin/env python3
"""
Training and evaluation script for the two custom full-scan person detectors.

DROW and DR-SPAAM use published pre-trained weights and are not trained here;
use evaluate.py --drow / --drspaam to evaluate them.

Trainable detectors
-------------------
  spacetime_cnn — SpaceTimeCNNDetector (2-D conv over N_beams×T grid)
  fullscan_tcn  — FullScanTCNDetector (causal temporal TCN over T + dilated CNN over beams)

Both are non-recursive (CNN/TCN only, no RNN/attention) and consume raw,
unaligned, single-channel range scans — see RESEARCH.md for why.

Eval-only
---------
  algorithmic          — AlgorithmicDetector (rule-based; see evaluate.py)

All detectors consume raw-scan input (optionally rotation-aligned):
  aligned_raw_scan(scans_hist, odoms_hist)  →  (T, N_beams, 1)  [default]
  raw_scan(scans_hist)                      →  (T, N_beams, 1)  [--no-align-scans]
  transposed to (N_beams, T, 1)

All detectors produce (default --head drow):
  logits : (N_beams, 4)   raw class logits  [bg, wc, wa, wp]
  votes  : (N_beams, 2)   vote offsets (dx, dy) in window space

With --head heatmap (all full-scan detectors; default for temporal_unet):
  heatmap : (N_beams, 1)  raw logit; sigmoid gives per-beam person probability.
  Decoded at eval time via scipy.signal.find_peaks(sigmoid(heatmap), height=0.3,
  distance=5).  See RESEARCH.md §2.3 ("Alternative detection head") for rationale.

Odometry alignment (--align-scans, default: on)
-----------------------------------------------
  Each historical scan in the T-frame window is fractionally shifted along the
  beam axis by the robot's yaw change, using drow_utils.aligned_raw_scan().
  When odom data is absent (FROG without odom files), shifts are zero and the
  result is identical to raw_scan().  Use --no-align-scans to disable.

Training losses
---------------
  --head drow:    Cross-entropy over 4 classes (class-weighted for background
                  imbalance) + MSE over vote offsets (positive beams only).
  --head heatmap: Weighted binary cross-entropy against a 1D Gaussian heatmap
                  target (sigma=--heatmap-sigma beams, default 2.0); pos_weight =
                  n_neg/n_pos clamped to 200.  Target generated by
                  make_heatmap_target(); loss by compute_heatmap_loss().

Usage
-----
  # Train SpaceTimeCNN on FROG for 10 epochs
  python train.py --detector spacetime_cnn --dataset frog --epochs 10

  # Train on DROW, evaluate AUC every 5 epochs
  python train.py --detector spacetime_cnn --dataset drow --auc-every 5

  # Evaluate a saved checkpoint
  python train.py --detector spacetime_cnn --weights out.pth --eval-only

  # Resume training
  python train.py --detector spacetime_cnn --resume out.pth --epochs 5

  # Train with early stopping and cosine LR schedule
  python train.py --detector spacetime_cnn --epochs 50 --patience 10 --lr-schedule cosine

  # Train FullScanTCN (causal temporal TCN + dilated spatial CNN)
  python train.py --detector fullscan_tcn --dataset frog --epochs 30

  # Train TemporalUNet (Architecture C — LFE-with-time, heatmap head by default)
  python train.py --detector temporal_unet --dataset frog --epochs 30

  # Disable odometry alignment (reproduce unaligned baseline for ablation)
  python train.py --detector spacetime_cnn --no-align-scans --epochs 30
"""

import argparse
import random
from pathlib import Path
from types import SimpleNamespace

import numpy as np
import torch
import torch.nn.functional as F
from torch.optim import Adam, Optimizer
from tqdm import tqdm
from sklearn.metrics import auc as sklearn_auc
from torch.utils.data import Dataset, DataLoader, Subset


# ---------------------------------------------------------------------------
# Device detection (CUDA → DirectML → CPU)
# ---------------------------------------------------------------------------

def detect_device():
    """
    Detect the best available compute device.

    Priority: CUDA / ROCm  →  DirectML  →  CPU.

    DirectML (``torch-directml``) enables hardware-accelerated training on any
    DX12-capable GPU on Windows without requiring CUDA or ROCm drivers.
    Install it with: ``pip install torch-directml``

    Returns
    -------
    device    : str or torch_directml device
        Passed to ``model.to(device)`` and ``tensor.to(device)``.
    using_dml : bool
        True when DirectML is active (informational; the training loop
        handles DML the same way as CUDA via standard ``.to()`` calls).
    """
    if torch.cuda.is_available():
        name = torch.cuda.get_device_name(0)
        n    = torch.cuda.device_count()
        print(f"CUDA / ROCm: {name}  ({n} device(s))")
        return "cuda", False

    try:
        import torch_directml
        dml = torch_directml.device()
        print(f"DirectML: {dml}")
        return dml, True
    except ImportError:
        pass

    print("No GPU found — using CPU.")
    return "cpu", False


# ---------------------------------------------------------------------------
# DML-safe Adam (avoids lerp_, addcmul_, and other unsupported fused ops)
# ---------------------------------------------------------------------------

class _DmlAdam(Optimizer):
    """
    Adam optimizer implemented with only basic DML-compatible ops.

    PyTorch's built-in Adam uses ``lerp_`` and ``addcmul_`` for speed; both
    fall back to CPU on DirectML.  This class replaces them with equivalent
    ``mul_`` + ``add_`` sequences that stay on the DML device throughout.

    Mathematically identical to standard Adam (Kingma & Ba, 2015) with the
    same ``lr``, ``betas``, ``eps``, and ``weight_decay`` semantics.
    """

    def __init__(self, params, lr: float = 1e-3,
                 betas: tuple = (0.9, 0.999), eps: float = 1e-8,
                 weight_decay: float = 0.0):
        defaults = dict(lr=lr, betas=betas, eps=eps, weight_decay=weight_decay)
        super().__init__(params, defaults)

    @torch.no_grad()
    def step(self, closure=None):
        loss = None
        if closure is not None:
            with torch.enable_grad():
                loss = closure()

        for group in self.param_groups:
            lr           = group["lr"]
            beta1, beta2 = group["betas"]
            eps          = group["eps"]
            wd           = group["weight_decay"]

            for p in group["params"]:
                if p.grad is None:
                    continue

                grad  = p.grad
                state = self.state[p]

                if len(state) == 0:
                    state["step"]       = 0
                    state["exp_avg"]    = torch.zeros_like(p)
                    state["exp_avg_sq"] = torch.zeros_like(p)

                state["step"] += 1
                t            = state["step"]
                exp_avg      = state["exp_avg"]
                exp_avg_sq   = state["exp_avg_sq"]

                # Optional L2 weight decay
                if wd != 0.0:
                    grad = grad.add(p, alpha=wd)

                # m_t = beta1 * m_{t-1} + (1 - beta1) * g_t
                # (replaces exp_avg.lerp_(grad, 1 - beta1))
                exp_avg.mul_(beta1).add_(grad, alpha=1.0 - beta1)

                # v_t = beta2 * v_{t-1} + (1 - beta2) * g_t^2
                # (replaces exp_avg_sq.mul_(beta2).addcmul_(grad, grad, …))
                exp_avg_sq.mul_(beta2).add_(grad * grad, alpha=1.0 - beta2)

                # Bias-corrected step size
                bias_c1   = 1.0 - beta1 ** t
                bias_c2   = 1.0 - beta2 ** t
                step_size = lr * (bias_c2 ** 0.5) / bias_c1

                # p = p - step_size * m_t / (sqrt(v_t) + eps)
                denom = exp_avg_sq.sqrt().add_(eps)
                p.addcdiv_(exp_avg, denom, value=-step_size)

        return loss


def _make_optimizer(params, lr: float, weight_decay: float,
                    using_dml: bool) -> Optimizer:
    """Return the right Adam variant for the active device."""
    if using_dml:
        return _DmlAdam(params, lr=lr, weight_decay=weight_decay)
    return Adam(params, lr=lr, weight_decay=weight_decay, foreach=True)

from follow_the_drow.detectors import (
    AlgorithmicDetector, DrowDetector, DrSpaamDetector,
    SpaceTimeCNNDetector, FullScanTCNDetector, TemporalUNetDetector,
    Li2FormerDetector,
    DETECTOR_REGISTRY,
)
from follow_the_drow.utils.drow_utils import (
    laser_angles, laser_minimum, laser_maximum, laser_increment,
    cutout, raw_scan, aligned_raw_scan,
    project_cartesian_from_polar, _win2global,
    votes_to_detections, _deep2flat, _process_detections,
)
from follow_the_drow.utils.tracking import SimpleTracker, odom_xya_delta_to_tracker_frame


# ---------------------------------------------------------------------------
# Dataset / configuration helpers
# ---------------------------------------------------------------------------

def _setup_datasets(args):
    """Load train and validation datasets; return (train_ds, val_ds, cfg)."""
    _time_frame_size = getattr(args, "time_frame", 5)
    if args.dataset == "frog":
        from follow_the_drow.datasets import FROG_Dataset, frog_laser_angles
        print(f"Loading FROG train split ('{args.train_split}') …")
        train_ds = FROG_Dataset(split=args.train_split, time_frame_size=_time_frame_size)
        val_ds = None
        if args.val_split:
            print(f"Loading FROG val split ('{args.val_split}') …")
            val_ds = FROG_Dataset(split=args.val_split, time_frame_size=_time_frame_size)
        cfg = SimpleNamespace(
            name="frog",
            angles_fn=frog_laser_angles,
            fov_min=FROG_Dataset.LASER_MIN_ANGLE,
            fov_max=FROG_Dataset.LASER_MAX_ANGLE,
            laser_inc=FROG_Dataset.LASER_INCREMENT,
        )
    elif args.dataset == "jrdb":
        from follow_the_drow.datasets import JRDB_Dataset, jrdb_laser_angles
        print(f"Loading JRDB split ('{args.train_split}') …")
        print("  NOTE: JRDB requires manual download — see JRDB_Dataset docstring.")
        train_ds = JRDB_Dataset(split=args.train_split)
        val_ds = None
        if args.val_split:
            print(f"Loading JRDB val split ('{args.val_split}') …")
            val_ds = JRDB_Dataset(split=args.val_split)
        cfg = SimpleNamespace(
            name="jrdb",
            angles_fn=jrdb_laser_angles,
            fov_min=JRDB_Dataset.LASER_MIN_ANGLE,
            fov_max=JRDB_Dataset.LASER_MAX_ANGLE,
            laser_inc=JRDB_Dataset.LASER_INCREMENT,
        )
    else:
        from follow_the_drow.datasets import DROW_Dataset
        from follow_the_drow.utils.file_utils import DROW_TRAIN_SET, DROW_VALIDATION_SET
        print("Loading DROW train set …")
        train_ds = DROW_Dataset(dataset=DROW_TRAIN_SET, time_frame_size=_time_frame_size)
        val_ds = None
        if args.val_split:
            print("Loading DROW val set …")
            val_ds = DROW_Dataset(dataset=DROW_VALIDATION_SET, time_frame_size=_time_frame_size)
        cfg = SimpleNamespace(
            name="drow",
            angles_fn=laser_angles,
            fov_min=laser_minimum,
            fov_max=laser_maximum,
            laser_inc=laser_increment,
        )

    n_train = sum(len(d) for d in train_ds.det_id)
    print(f"  Train: {len(train_ds.scan_id)} seq, {n_train} annotated frames")
    if val_ds is not None:
        n_val = sum(len(d) for d in val_ds.det_id)
        print(f"  Val:   {len(val_ds.scan_id)} seq, {n_val} annotated frames")
    print()
    return train_ds, val_ds, cfg


def _build_model(args):
    """
    Instantiate the requested detector with all hyperparameters.

    Supports architecture tuning for the full-scan models:
      --dropout            applied to all models (default 0.5)
      --backbone-channels  DilatedScanBackbone channels (FullScanTCN; default 64)
      --channels           internal channel width (SpaceTimeCNN; default 96)
      --n-spatial-stages   spatial inception stages 1–4 (SpaceTimeCNN; default 3)
      --tcn-channels       temporal TCN channel width (FullScanTCN; default 64)
      --unet-channels      base channels for TemporalUNet encoder (default 32)
    """
    det = args.detector
    dr  = getattr(args, "dropout",           0.5)
    bc  = getattr(args, "backbone_channels", 64)
    ch  = getattr(args, "channels",          96)
    nss = getattr(args, "n_spatial_stages",  3)
    tf  = getattr(args, "time_frame",        5)
    tcc = getattr(args, "tcn_channels",      64)
    uc  = getattr(args, "unet_channels",     32)

    if det == "drow":
        return DrowDetector(dropout=dr, time_frame_size=tf, verbose=False)
    if det == "drspaam":
        return DrSpaamDetector(dropout=dr, num_scans=tf)
    if det == "li2former":
        return Li2FormerDetector(dropout=dr, num_scans=tf)
    # Full-scan models share the --head flag; temporal_unet defaults to heatmap.
    hd  = getattr(args, "head", "heatmap" if det == "temporal_unet" else "drow")
    if det == "spacetime_cnn":
        return SpaceTimeCNNDetector(n_time=tf, channels=ch,
                                    n_spatial_stages=nss, dropout=dr, head=hd)
    if det == "fullscan_tcn":
        return FullScanTCNDetector(n_time=tf, tcn_channels=tcc,
                                   backbone_channels=bc, dropout=dr, head=hd)
    if det == "temporal_unet":
        return TemporalUNetDetector(n_time=tf, unet_channels=uc, dropout=dr, head=hd)
    raise ValueError(f"'{det}' cannot be trained (algorithmic and LFE detectors are eval-only)")


def _freeze_backbone(net) -> None:
    """
    Freeze every parameter except the final output head(s) (head_logits/
    head_votes/head_heatmap), in place. Intended for --init-weights fine-
    tuning: a full unfrozen fine-tune from FROG weights regressed *below*
    zero-shot transfer (14.6% vs 26.7-28.0% wp-AUC), plausibly catastrophic
    forgetting -- unfreezing the whole network lets a few epochs on DROW's
    tiny (17.6k-frame) training set overwrite the more general local-shape
    features FROG's much larger dataset taught it. Freezing everything but
    the head keeps those features fixed and only re-fits the final
    classification/regression mapping on top of them. See
    docs/IDEAS_BACKLOG.md item 5.
    """
    n_frozen = n_trainable = 0
    for name, p in net.named_parameters():
        if name.startswith("head_"):
            n_trainable += p.numel()
            continue
        p.requires_grad = False
        n_frozen += p.numel()
    print(f"  Backbone frozen: {n_frozen:,} params fixed, "
          f"{n_trainable:,} params trainable (head only)\n")


# ---------------------------------------------------------------------------
# Ground-truth target generation
# ---------------------------------------------------------------------------

def make_targets(scan: np.ndarray, angles: np.ndarray,
                 gt_per_class: dict, vote_collect_radius: float = 0.6):
    """
    Compute per-beam class labels and vote-offset targets.

    Parameters
    ----------
    scan          : (N,)  range measurements
    angles        : (N,)  beam angles in radians
    gt_per_class  : {class_id: [(r, phi), ...]}  1=wc, 2=wa, 3=wp
    vote_collect_radius : radius (m) around GT that marks a beam as positive

    Returns
    -------
    labels       : (N,) int64
    vote_targets : (N, 2) float32  — (dx, dy) in window space
    """
    scan   = np.asarray(scan,   dtype=np.float64)
    angles = np.asarray(angles, dtype=np.float64)
    N = len(scan)
    labels       = np.zeros(N, dtype=np.int64)
    vote_targets = np.zeros((N, 2), dtype=np.float32)

    beam_x = scan * -np.sin(angles)
    beam_y = scan *  np.cos(angles)

    for class_id, anns in sorted(gt_per_class.items()):
        for r_gt, phi_gt in anns:
            x_gt = r_gt * -np.sin(phi_gt)
            y_gt = r_gt *  np.cos(phi_gt)
            dist = np.sqrt((x_gt - beam_x) ** 2 + (y_gt - beam_y) ** 2)
            mask = dist < vote_collect_radius
            if not np.any(mask):
                continue
            labels[mask] = class_id
            dphi = phi_gt - angles[mask]
            vote_targets[mask, 0] = r_gt * np.sin(dphi)
            vote_targets[mask, 1] = r_gt * np.cos(dphi) - scan[mask]

    return labels, vote_targets


# ---------------------------------------------------------------------------
# Heatmap target generation
# ---------------------------------------------------------------------------

def make_heatmap_target(scan: np.ndarray, angles: np.ndarray,
                        gt_per_class: dict, sigma_beams: float = 2.0) -> np.ndarray:
    """
    Build a soft Gaussian heatmap target over N_beams.

    Each annotated person contributes a unit Gaussian centred at the beam
    whose Cartesian position is nearest to the annotation.  Gaussians from
    all persons are summed then clipped to [0, 1] so overlapping annotations
    saturate cleanly rather than exceeding 1.

    Parameters
    ----------
    scan          : (N,) range measurements
    angles        : (N,) beam angles in radians
    gt_per_class  : {class_id: [(r, phi), ...]}
    sigma_beams   : Gaussian width in beam units (default 2 → ≈1° FWHM at 0.5°/beam)

    Returns
    -------
    (N,) float32 in [0, 1]
    """
    N = len(scan)
    heatmap      = np.zeros(N, dtype=np.float32)
    beam_x       = scan * -np.sin(angles)
    beam_y       = scan *  np.cos(angles)
    beam_indices = np.arange(N, dtype=np.float32)

    for anns in gt_per_class.values():
        for r_gt, phi_gt in anns:
            x_gt = r_gt * -np.sin(phi_gt)
            y_gt = r_gt *  np.cos(phi_gt)
            dist = np.sqrt((x_gt - beam_x) ** 2 + (y_gt - beam_y) ** 2)
            center_beam = int(np.argmin(dist))
            gauss = np.exp(-0.5 * ((beam_indices - center_beam) / sigma_beams) ** 2)
            heatmap += gauss.astype(np.float32)

    return np.clip(heatmap, 0.0, 1.0)


# ---------------------------------------------------------------------------
# Loss
# ---------------------------------------------------------------------------

def compute_heatmap_loss(heatmap_pred: torch.Tensor,
                         heatmap_target: torch.Tensor) -> torch.Tensor:
    """
    heatmap_pred   : (N,) raw logits before sigmoid
    heatmap_target : (N,) float32 in [0, 1]  (Gaussian heatmap from make_heatmap_target)

    Weighted BCE: beams inside any person's Gaussian (target > 0.1) are
    upweighted relative to background beams to compensate for the ≈50:1
    background/foreground imbalance typical in 720-beam FROG scans with 1–3
    persons per frame.
    """
    n_pos = (heatmap_target > 0.1).float().sum()
    n_neg = (heatmap_target <= 0.1).float().sum()
    pw = (n_neg / n_pos.clamp(min=1.0)).clamp(max=200.0)
    return F.binary_cross_entropy_with_logits(
        heatmap_pred, heatmap_target,
        pos_weight=torch.tensor([pw.item()], device=heatmap_pred.device),
    )


def compute_loss(logits: torch.Tensor, votes: torch.Tensor,
                 labels: torch.Tensor, vote_targets: torch.Tensor,
                 vote_weight: float = 0.02):
    """
    logits       : (N, C)  raw class logits; C=4 for multi-class, C=1 for binary
    votes        : (N, 2)  predicted vote offsets
    labels       : (N,)    int64 target class indices  (0=bg, 1=wc, 2=wa, 3=wp)
    vote_targets : (N, 2)  target vote offsets

    Binary mode (C=1, e.g. Li2Former): any non-background beam is treated as
    positive; loss is binary cross-entropy with class-balanced pos_weight.
    """
    n_pos = int((labels > 0).sum())
    n_neg = int((labels == 0).sum())

    if logits.shape[-1] == 1:
        # Binary classification: background (0) vs. any person (1)
        binary_labels = (labels > 0).float()
        pos_weight = (
            torch.tensor([float(n_neg) / float(n_pos)], device=logits.device)
            if n_pos > 0 and n_neg > 0 else None
        )
        l_class = F.binary_cross_entropy_with_logits(
            logits.squeeze(-1), binary_labels, pos_weight=pos_weight
        )
    else:
        if n_pos > 0 and n_neg > 0:
            pos_weight = float(n_neg) / float(n_pos)
            weight = torch.ones(logits.shape[-1], device=logits.device)
            weight[1:] = pos_weight
        else:
            weight = None
        l_class = F.cross_entropy(logits, labels, weight=weight)

    pos_mask = labels > 0
    if pos_mask.any():
        l_vote = F.mse_loss(votes[pos_mask], vote_targets[pos_mask])
    else:
        l_vote = logits.new_tensor(0.0)

    loss = l_class + vote_weight * l_vote
    return loss, l_class.item(), l_vote.item()



# ---------------------------------------------------------------------------
# Input extraction (detector-type aware)
# ---------------------------------------------------------------------------

def _local_normalize(r: np.ndarray, window: int = 21) -> np.ndarray:
    """
    Subtract a local (beam-neighbourhood) moving-average reference -- computed
    once from the current frame, applied to every temporal slice -- from every
    beam. Unlike _global_normalize()'s single whole-frame scalar, this varies
    per beam, so it targets DR-SPAAM's actual per-beam centering property
    (each cutout is normalized against its own local surroundings, not the
    whole scan) while staying a single cheap elementwise/local-window pass
    before the one full-scan conv forward pass -- not DR-SPAAM's expensive
    independent per-beam network calls. Edge beams use a replicate-padded
    window so the local mean stays well-defined at the FoV boundary. See
    docs/IDEAS_BACKLOG.md item 5.
    """
    ref_frame = r[-1, :, 0]                          # (N,) current frame
    n = ref_frame.shape[0]
    half = window // 2
    padded = np.pad(ref_frame, (half, half), mode="edge")
    kernel = np.ones(window, dtype=np.float32) / window
    local_mean = np.convolve(padded, kernel, mode="valid")  # (N,)
    if local_mean.shape[0] != n:
        # window is even: 'valid' length is n+1 -- drop the extra tap so the
        # reference stays aligned one-to-one with ref_frame's own beams.
        local_mean = local_mean[: n]
    return r - local_mean[None, :, None]


def _global_normalize(r: np.ndarray) -> np.ndarray:
    """
    Subtract a single whole-frame reference (the current frame's mean range)
    from every beam of every temporal slice. The cheap, uniform counterpart
    to per-beam local centering (DR-SPAAM's cutout() approach): removes "how
    far away is this room on average" as a memorizable per-scene shortcut,
    without touching per-beam relative shape or frame-to-frame differences
    (the same constant is subtracted everywhere, so those are unaffected).
    Diagnostic per docs/IDEAS_BACKLOG.md item 5: weaker than per-beam
    centering by design (position is still untouched) -- run alongside it to
    see how much of any gain is explained by scale/room-depth alone.
    """
    ref = r[-1].mean()
    return r - ref


def _diff_encode(r: np.ndarray) -> np.ndarray:
    """
    Replace a (T, N, 1) stack of raw/aligned frames with an explicit-motion
    encoding of the same shape: the last T-1 slots become frame-to-frame
    differences (diffs[t] = r[t+1] - r[t], how the scan changed moving from
    frame t to t+1) and the final slot stays the raw current frame -- so the
    network gets one absolute reference plus T-1 motion channels instead of
    T repeated near-absolute snapshots. A static background nets to ~0 in
    every diff channel; a moving person doesn't. Shape-preserving (still
    (T, N, 1)), so no architecture change is needed to use it. See
    docs/IDEAS_BACKLOG.md item 5.
    """
    if r.shape[0] < 2:
        return r
    diffs = r[1:] - r[:-1]           # (T-1, N, 1)
    current = r[-1:]                  # (1, N, 1)
    return np.concatenate([diffs, current], axis=0)  # (T, N, 1)


def _extract_input(net, scan, scans_hist, odoms_hist, angles, cfg, device,
                   align_scans: bool = True, zero_history: bool = False,
                   diff_channels: bool = False, global_normalize: bool = False,
                   local_normalize_window: int = 0):
    """
    Build the model input tensor from raw scan data.

    Cutout-based detectors → (N_beams, T, N_SAMP)  (always uses odometry alignment
                              via cutout()'s built-in rotation correction)
    Full-scan detectors    → (N_beams, T, 1)
                              With align_scans=True (default): rotation-corrected via
                              aligned_raw_scan(); falls back to raw_scan() if odoms
                              are zero (FROG without odom file).
                              With align_scans=False: raw_scan() — no odometry used.

    zero_history: ablation flag — zero every historical frame (all but the
    last/current one) before feature extraction, so the model only ever sees
    real data from the current scan. Used to measure how much the temporal
    window actually contributes vs. a single-frame-equivalent input, with the
    architecture (T dimension, parameter count) held fixed.

    diff_channels, global_normalize: raw_scan-mode only -- see _diff_encode()/
    _global_normalize(). Both representation choices, not augmentations: must
    be applied identically at train and eval time, unlike beam_shift_aug.
    """
    if zero_history:
        scans_hist = scans_hist.copy()
        scans_hist[:-1] = 0.0
    if getattr(net, "INPUT_MODE", "cutout") == "raw_scan":
        if align_scans:
            r = aligned_raw_scan(scans_hist, odoms_hist, cfg.laser_inc, angles=angles)
        else:
            r = raw_scan(scans_hist)
        if diff_channels:
            r = _diff_encode(r)
        if global_normalize:
            r = _global_normalize(r)
        if local_normalize_window > 0:
            r = _local_normalize(r, local_normalize_window)
        return torch.from_numpy(r.transpose(1, 0, 2)).to(device)  # (N_beams, T, 1)
    else:
        nsamp       = getattr(net, "N_SAMP", DrowDetector.N_SAMP)
        win_sz      = getattr(net, "WIN_SZ", 1.66)
        thresh_dist = getattr(net, "THRESH_DIST", 1)
        cut = cutout(scans_hist, odoms_hist, len(scan),
                     win_sz=win_sz, thresh_dist=thresh_dist,
                     nsamp=nsamp, laserIncrement=cfg.laser_inc)
        return torch.from_numpy(cut).to(device)                   # (N_beams, T, N_SAMP)


# ---------------------------------------------------------------------------
# Cached frame dataset  (speeds up multi-epoch training by ~2–4×)
# ---------------------------------------------------------------------------

def _shift_beams(t: torch.Tensor, shift: int) -> torch.Tensor:
    """
    Shift a (N, ...) tensor along its beam axis by `shift` positions,
    edge-clamping the revealed boundary (repeats the boundary value, same
    convention DROW_Dataset.get_scan() already uses for its own out-of-range
    clamping). new[i] = old[i - shift] -- content moves toward higher index
    (physically "left") for shift > 0.

    Applied post-hoc to make_targets()/aligned_raw_scan()/cutout()'s already-
    computed outputs rather than to the raw scan+GT inputs: labels and vote
    offsets are stored per beam-index slot, and vote_targets' (dx, dy) values
    are already relative to whichever beam holds them, so relabeling which
    slot holds which value is a self-contained permutation -- it doesn't need
    to re-derive any angle-dependent geometry, and so can't reintroduce the
    kind of sign bug aligned_raw_scan()'s own beam-index shift had.
    """
    if shift == 0:
        return t
    n = t.shape[0]
    idx = torch.clamp(torch.arange(n, device=t.device) - shift, 0, n - 1)
    return t[idx]


def _jitter_range(x: torch.Tensor, scale_eps: float, offset_delta: float) -> torch.Tensor:
    """
    Multiplicative scale + additive offset jitter on the input tensor only --
    training-time augmentation forcing robustness to small absolute range/
    scale perturbations. Deliberately does NOT touch labels/vote_targets:
    those encode a geometric relationship (where's the person relative to
    this beam) that's still approximately valid under jitter this small
    (scale_eps, offset_delta both meant to be small relative to
    vote_collect_radius), the same way image-classification brightness/
    contrast jitter perturbs pixels without relabeling the image. See
    docs/IDEAS_BACKLOG.md item 5.
    """
    if scale_eps <= 0 and offset_delta <= 0:
        return x
    scale  = 1.0 + random.uniform(-scale_eps, scale_eps) if scale_eps > 0 else 1.0
    offset = random.uniform(-offset_delta, offset_delta) if offset_delta > 0 else 0.0
    return x * scale + offset


class LidarFrameDataset(Dataset):
    """
    One item = one annotated lidar frame, preprocessed (cutout or raw_scan)
    on every access.

    By default (``cache=True``) the result is also stored in ``_cache`` on
    first access, so later epochs are pure dict lookups with no NumPy
    preprocessing — ~2-4x faster, at the cost of holding every frame in RAM
    for the lifetime of the dataset.  Memory per frame (raw_scan mode,
    FROG 720 beams): ~25 KB (1 channel, vs. ~53 KB for the earlier 3-channel
    aligned representation); cutout mode is much larger because it stores
    raw per-beam samples instead of a single value per beam — ~675 KB
    (FROG, 720 beams) / ~430 KB (DROW, 450 beams).  For FROG's full train
    split (108k frames) that's still ~2.6 GB in raw_scan mode, before
    accounting for the val split, the model, or anything else — pass
    ``cache=False`` to recompute every access instead and trade training
    time for that memory back on RAM-constrained machines.

    beam_shift_aug (0 = off): training-only data augmentation. Every access
    applies a *fresh* random beam-index roll (uniform in
    [-beam_shift_aug, beam_shift_aug]) to the cached/freshly-built tensors,
    so the same underlying frame lands at a different absolute beam index
    each epoch -- intended to break the "this absolute beam index = this
    room's doorway" shortcut a small, fixed-room-count training set makes
    possible (see docs/IDEAS_BACKLOG.md item 5). Cheap: applied to the small
    (N, ...) output tensors, after the cache lookup, so it doesn't defeat
    caching the way augmenting the raw inputs before make_targets()/
    aligned_raw_scan() would (those would need recomputing every epoch).

    Parameters
    ----------
    dataset     : DROW_Dataset or FROG_Dataset
    cfg         : SimpleNamespace with angles_fn and laser_inc
    input_mode  : "cutout" or "raw_scan"
    vote_radius : positive-beam radius around GT (same as vote_collect_radius)
    nsamp       : number of cutout samples per beam (ignored for raw_scan)
    cache       : keep preprocessed frames in RAM across epochs (default: True)
    beam_shift_aug : max random beam-index roll applied per access, 0 = off
    """

    def __init__(self, dataset, cfg, input_mode: str,
                 vote_radius: float, nsamp: int = 48, cache: bool = True,
                 head: str = "drow", heatmap_sigma: float = 2.0,
                 align_scans: bool = True, zero_history: bool = False,
                 dtime: int = 1, beam_shift_aug: int = 0,
                 diff_channels: bool = False, global_normalize: bool = False,
                 local_normalize_window: int = 0,
                 range_jitter_scale: float = 0.0, range_jitter_offset: float = 0.0):
        self._dataset       = dataset
        self._cfg           = cfg
        self._input_mode    = input_mode
        self._vote_radius   = vote_radius
        self._nsamp         = nsamp
        self._cache_enabled = cache
        self._head          = head
        self._heatmap_sigma = heatmap_sigma
        # Only apply alignment when consuming raw_scan format; cutout() has its own
        # built-in rotation correction and does not use this flag.
        self._align_scans   = align_scans and (input_mode == "raw_scan")
        # Ablation: zero every historical frame so training only ever sees
        # real data from the current scan — see _extract_input()'s docstring.
        self._zero_history  = zero_history
        # Stride (in raw scans) between the dataset.time_frame frames fetched
        # per sample — see DROW_Dataset.get_scan()/FROG_Dataset.get_scan().
        # dtime=1 (default): consecutive frames, the original behaviour.
        self._dtime          = dtime
        self._beam_shift_aug = beam_shift_aug
        # Representation choices, not augmentations -- must match at eval
        # time (see evaluate_auc()'s own diff_channels/global_normalize params).
        self._diff_channels  = diff_channels
        self._global_normalize = global_normalize
        self._local_normalize_window = local_normalize_window
        # Training-only augmentation (like beam_shift_aug): applied fresh per
        # access in _augment(), to x only, never at eval time.
        self._range_jitter_scale  = range_jitter_scale
        self._range_jitter_offset = range_jitter_offset
        self._angles        = cfg.angles_fn(dataset.scans[0].shape[1])
        self.indices      = [
            (seq, det_idx)
            for seq in range(len(dataset.det_id))
            for det_idx in range(len(dataset.det_id[seq]))
        ]
        self._cache: dict = {}

    def __len__(self) -> int:
        return len(self.indices)

    def __getitem__(self, idx: int):
        if self._cache_enabled and idx in self._cache:
            return self._augment(self._cache[idx])

        seq, det_idx = self.indices[idx]
        ds    = self._dataset
        iscan = ds.idet2iscan[seq][det_idx]
        scan  = ds.scans[seq][iscan]
        scans_hist, odoms_hist = ds.get_scan(seq, iscan, ds.time_frame, dtime=self._dtime)
        if self._zero_history:
            scans_hist = scans_hist.copy()
            scans_hist[:-1] = 0.0

        gt_per_class = {
            1: ds.det_wc[seq][det_idx],
            2: ds.det_wa[seq][det_idx],
            3: ds.det_wp[seq][det_idx],
        }
        labels, vote_targets = make_targets(
            scan, self._angles, gt_per_class, self._vote_radius)

        if self._input_mode == "raw_scan":
            if self._align_scans:
                arr = aligned_raw_scan(scans_hist, odoms_hist, self._cfg.laser_inc, angles=self._angles)
            else:
                arr = raw_scan(scans_hist)
            if self._diff_channels:
                arr = _diff_encode(arr)
            if self._global_normalize:
                arr = _global_normalize(arr)
            if self._local_normalize_window > 0:
                arr = _local_normalize(arr, self._local_normalize_window)
            x = torch.from_numpy(
                np.asarray(arr, dtype=np.float32).transpose(1, 0, 2))  # (N,T,1)
        else:
            arr = cutout(scans_hist, odoms_hist, len(scan),
                         nsamp=self._nsamp,
                         laserIncrement=self._cfg.laser_inc)
            x = torch.from_numpy(np.asarray(arr, dtype=np.float32))    # (N,T,S)
        result = (x, torch.from_numpy(labels), torch.from_numpy(vote_targets))
        if self._head == "heatmap":
            hm = make_heatmap_target(scan, self._angles, gt_per_class,
                                     self._heatmap_sigma)
            result = result + (torch.from_numpy(hm),)
        if self._cache_enabled:
            self._cache[idx] = result
        return self._augment(result)

    def _augment(self, result: tuple) -> tuple:
        """Apply fresh random training-only augmentation to an (already
        cached-or-not) result tuple: a beam-index roll (see beam_shift_aug)
        applied to every tensor, then range scale/offset jitter (see
        _jitter_range) applied to x only -- labels/vote_targets stay the
        clean geometric ground truth."""
        if self._beam_shift_aug > 0:
            shift = random.randint(-self._beam_shift_aug, self._beam_shift_aug)
            if shift != 0:
                result = tuple(_shift_beams(t, shift) for t in result)
        if self._range_jitter_scale > 0 or self._range_jitter_offset > 0:
            x, *rest = result
            x = _jitter_range(x, self._range_jitter_scale, self._range_jitter_offset)
            result = (x, *rest)
        return result


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------

def train_epoch(net, frame_ds: LidarFrameDataset, optimizer,
                vote_weight: float, subsample: float = 1.0,
                device: str = "cpu", batch_size: int = 4):
    """One training epoch using the cached LidarFrameDataset."""
    if subsample < 1.0:
        n = max(1, int(len(frame_ds) * subsample))
        idx = random.sample(range(len(frame_ds)), n)
        ds = Subset(frame_ds, idx)
    else:
        ds = frame_ds

    loader = DataLoader(ds, batch_size=batch_size, shuffle=True, num_workers=0)

    net.train()
    total_loss = class_loss = vote_loss = 0.0
    n_steps = 0
    pbar = tqdm(loader, desc="  train", unit="fr", leave=False, dynamic_ncols=True)

    _beam_batch = getattr(net, "BEAM_BATCH", False)
    _head_type  = getattr(net, "head_type", "drow")
    for batch in pbar:
        if _head_type == "heatmap":
            x, labels, votes, hm_tgt = batch
        else:
            x, labels, votes = batch
        B, N = x.shape[:2]
        # BEAM_BATCH models (DrSpaamDetector) need (B, N, T, S) so that spatial
        # attention sees all N beams of one scan together.  Other models use the
        # flattened (B*N, T, S) as before.
        x_in  = x.to(device) if _beam_batch else x.reshape(B*N, *x.shape[2:]).to(device)
        if _head_type == "heatmap":
            (heatmap,) = net(x_in)                               # (B*N, 1)
            hm_flat    = hm_tgt.reshape(B * N).to(device)
            loss       = compute_heatmap_loss(heatmap.squeeze(-1), hm_flat)
            lc, lv     = loss.item(), 0.0
        else:
            l_flat         = labels.reshape(B * N).to(device)
            v_flat         = votes.reshape(B * N, 2).to(device)
            logits, vpred  = net(x_in)
            loss, lc, lv   = compute_loss(logits, vpred, l_flat, v_flat, vote_weight)
        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
        class_loss += lc
        vote_loss  += lv
        n_steps    += 1
        pbar.set_postfix(loss=f"{total_loss / n_steps:.4f}", refresh=False)

    n = max(n_steps, 1)
    return total_loss / n, class_loss / n, vote_loss / n


# ---------------------------------------------------------------------------
# Evaluation
# ---------------------------------------------------------------------------

def evaluate_loss(net, frame_ds: LidarFrameDataset, vote_weight: float,
                  subsample: float = 1.0, device: str = "cpu",
                  batch_size: int = 4):
    """Compute average loss on a cached LidarFrameDataset (no gradient)."""
    if subsample < 1.0:
        n = max(1, int(len(frame_ds) * min(subsample * 2, 1.0)))
        idx = random.sample(range(len(frame_ds)), n)
        ds = Subset(frame_ds, idx)
    else:
        ds = frame_ds

    loader = DataLoader(ds, batch_size=batch_size, shuffle=False, num_workers=0)

    net.eval()
    total_loss = class_loss = vote_loss = 0.0
    n_steps = 0
    pbar = tqdm(loader, desc="    val", unit="fr", leave=False, dynamic_ncols=True)

    _beam_batch = getattr(net, "BEAM_BATCH", False)
    _head_type  = getattr(net, "head_type", "drow")
    with torch.no_grad():
        for batch in pbar:
            if _head_type == "heatmap":
                x, labels, votes, hm_tgt = batch
            else:
                x, labels, votes = batch
            B, N = x.shape[:2]
            x_in  = x.to(device) if _beam_batch else x.reshape(B*N, *x.shape[2:]).to(device)
            if _head_type == "heatmap":
                (heatmap,) = net(x_in)
                hm_flat    = hm_tgt.reshape(B * N).to(device)
                loss       = compute_heatmap_loss(heatmap.squeeze(-1), hm_flat)
                lc, lv     = loss.item(), 0.0
            else:
                l_flat         = labels.reshape(B * N).to(device)
                v_flat         = votes.reshape(B * N, 2).to(device)
                logits, vpred  = net(x_in)
                loss, lc, lv   = compute_loss(logits, vpred, l_flat, v_flat, vote_weight)
            total_loss += loss.item()
            class_loss += lc
            vote_loss  += lv
            n_steps    += 1
            pbar.set_postfix(loss=f"{total_loss / n_steps:.4f}", refresh=False)

    n = max(n_steps, 1)
    return total_loss / n, class_loss / n, vote_loss / n


def _safe_auc(recs, precs):
    mask = ~np.isnan(recs) & ~np.isnan(precs)
    r, p = recs[mask], precs[mask]
    if len(r) < 2:
        return float("nan")
    order = np.argsort(r)
    return float(sklearn_auc(r[order], p[order]))


def evaluate_auc(net, dataset, cfg, eval_r: float = 0.5,
                 v2d_conf: dict = None, device: str = "cpu",
                 batch_size: int = 1, align_scans: bool = True,
                 zero_history: bool = False, dtime: int = 1,
                 diff_channels: bool = False, global_normalize: bool = False,
                 local_normalize_window: int = 0,
                 return_curves: bool = False, tracker_kwargs: dict = None):
    """
    Run full inference on every annotated frame and compute per-class AUC.

    Works with any detector that has INPUT_MODE set ("cutout" or "raw_scan").

    Returns a dict with keys 'agnostic', 'wc', 'wa', 'wp'.
    """
    if v2d_conf is None:
        v2d_conf = {
            "blur_sigma":          2.0,
            "blur_win":            11,
            "bin_size":            0.1,
            "vote_collect_radius": 0.5,
            "min_thresh":          1e-3,
        }

    net.eval()
    _head_type = getattr(net, "head_type", "drow")

    all_confs, all_votes_raw = [], []
    all_heatmaps             = []          # populated only for heatmap head
    all_scans_for_pr         = []
    all_wcs, all_was, all_wps = [], [], []

    n_frames = sum(len(dataset.det_id[seq]) for seq in range(len(dataset.det_id)))

    all_pairs = [
        (seq, det_idx)
        for seq in range(len(dataset.det_id))
        for det_idx in range(len(dataset.det_id[seq]))
    ]

    _angles = cfg.angles_fn(dataset.scans[0].shape[1])

    with torch.no_grad():
        pbar = tqdm(total=n_frames, desc="    AUC", unit="fr",
                    leave=False, dynamic_ncols=True)

        buf_x, buf_meta = [], []

        _beam_batch = getattr(net, "BEAM_BATCH", False)

        def _flush_auc():
            if _beam_batch:
                x_bat = torch.stack(buf_x, dim=0)
            else:
                x_bat = torch.cat(buf_x, dim=0)
            n_beams = buf_x[0].shape[0]

            if _head_type == "heatmap":
                (heatmap,) = net(x_bat)                              # (B*N_beams, 1)
                hm_np = torch.sigmoid(heatmap).squeeze(-1).cpu().numpy()
                for i, (scan_i, wc_i, wa_i, wp_i) in enumerate(buf_meta):
                    s, e = i * n_beams, (i + 1) * n_beams
                    all_heatmaps.append(hm_np[s:e])
                    all_scans_for_pr.append(scan_i)
                    all_wcs.append(wc_i); all_was.append(wa_i); all_wps.append(wp_i)
            else:
                logits, vpred = net(x_bat)
                if logits.shape[-1] == 1:
                    # pedestrian_only weights: sigmoid + expand to 4-class
                    prob  = torch.sigmoid(logits)
                    confs = torch.zeros(logits.shape[0], 4, device=logits.device)
                    confs[:, 3] = prob[:, 0]
                    confs_np = confs.cpu().numpy()
                else:
                    confs_np = F.softmax(logits, dim=-1).cpu().numpy()
                votes_np = vpred.cpu().numpy()
                for i, (scan_i, wc_i, wa_i, wp_i) in enumerate(buf_meta):
                    s, e = i * n_beams, (i + 1) * n_beams
                    all_confs.append(confs_np[s:e])
                    all_votes_raw.append(votes_np[s:e])
                    all_scans_for_pr.append(scan_i)
                    all_wcs.append(wc_i); all_was.append(wa_i); all_wps.append(wp_i)
            buf_x.clear(); buf_meta.clear()

        # Some published checkpoints (e.g. DR-SPAAM's dr_spaam_e40.pth) were
        # trained with a longer temporal window than dataset.time_frame — the
        # network's own num_scans (when present) takes precedence so the
        # auto-regressive template gets the refinement depth it expects.
        _time_frame = getattr(net, "num_scans", dataset.time_frame)

        for seq, det_idx in all_pairs:
            iscan = dataset.idet2iscan[seq][det_idx]
            scan  = dataset.scans[seq][iscan]
            scans_hist, odoms_hist = dataset.get_scan(seq, iscan, _time_frame, dtime=dtime)

            buf_x.append(_extract_input(net, scan, scans_hist, odoms_hist,
                                        _angles, cfg, device,
                                        align_scans=align_scans,
                                        zero_history=zero_history,
                                        diff_channels=diff_channels,
                                        global_normalize=global_normalize,
                                        local_normalize_window=local_normalize_window))
            buf_meta.append((scan,
                             dataset.det_wc[seq][det_idx],
                             dataset.det_wa[seq][det_idx],
                             dataset.det_wp[seq][det_idx]))
            pbar.update(1)
            if len(buf_x) >= batch_size:
                _flush_auc()

        if buf_x:
            _flush_auc()
        pbar.close()

    # ------------------------------------------------------------------ #
    # Decode raw model outputs → (det_x, det_y, det_p, det_f)            #
    # ------------------------------------------------------------------ #
    if _head_type == "heatmap":
        from scipy.signal import find_peaks
        det_x_l, det_y_l, det_p_l, det_f_l = [], [], [], []
        for frame_idx, (hm, scan) in enumerate(zip(all_heatmaps, all_scans_for_pr)):
            peaks, _ = find_peaks(hm, height=0.3, distance=5)
            for pk in peaks:
                r   = float(scan[pk])
                phi = float(_angles[pk])
                det_x_l.append(r * -np.sin(phi))
                det_y_l.append(r *  np.cos(phi))
                det_p_l.append(float(hm[pk]))
                det_f_l.append(frame_idx)
        del all_heatmaps, all_scans_for_pr
        det_x = np.array(det_x_l, dtype=np.float32)
        det_y = np.array(det_y_l, dtype=np.float32)
        det_f = np.array(det_f_l, dtype=np.int64)
        # _process_detections expects (N_dets, 4) — place confidence in person
        # column (index 3); agnostic score = sum(det_p[:,1:]) = det_p[:,3].
        det_p = np.zeros((len(det_x_l), 4), dtype=np.float32)
        if len(det_x_l):
            det_p[:, 3] = det_p_l
        del det_x_l, det_y_l, det_p_l, det_f_l
    else:
        all_x_votes, all_y_votes = [], []
        for scan, vots in zip(all_scans_for_pr, all_votes_raw):
            r_new, phi_new = _win2global(
                scan[None], _angles[None],
                vots[None, :, 0], vots[None, :, 1],
            )
            all_x_votes.append(r_new * -np.sin(phi_new))
            all_y_votes.append(r_new *  np.cos(phi_new))
        # Free per-frame lists before concatenating to avoid peak triple-memory.
        del all_scans_for_pr, all_votes_raw
        x_arr = np.concatenate(all_x_votes, axis=0)
        y_arr = np.concatenate(all_y_votes, axis=0)
        del all_x_votes, all_y_votes
        p_arr = np.stack(all_confs, axis=0)
        del all_confs
        detections = votes_to_detections(x_arr, y_arr, p_arr, **v2d_conf)
        det_x, det_y, det_p, det_f = _deep2flat(detections)

    if tracker_kwargs is not None:
        # Late-fusion temporal tracker over this model's own per-frame "wp"
        # (person) detections — a post-hoc, no-retraining filter, run in
        # frame order with the tracker reset at sequence boundaries. Only
        # the wp confidence column is tracked (FROG, the dataset this was
        # built for, has no wc/wa annotations anyway); other columns are
        # zeroed. See library/follow_the_drow/utils/tracking.py.
        by_frame: dict = {}
        for i in range(len(det_f)):
            by_frame.setdefault(int(det_f[i]), []).append(
                (float(det_p[i, 3]), float(det_x[i]), float(det_y[i])))

        new_x, new_y, new_p, new_f = [], [], [], []
        tracker, prev_seq = None, object()
        prev_theta, prev_wx, prev_wy = 0.0, 0.0, 0.0
        for frame_idx, (seq, det_idx) in enumerate(all_pairs):
            iscan = dataset.idet2iscan[seq][det_idx]
            wxya = dataset.odoms[seq][iscan]["xya"]
            theta, wx, wy = float(wxya[2]), float(wxya[0]), float(wxya[1])
            if seq != prev_seq:
                tracker, prev_seq = SimpleTracker(**tracker_kwargs), seq
                prev_theta, prev_wx, prev_wy = theta, wx, wy
            # Real per-frame heading/translation delta where odometry exists
            # (DROW); naturally 0.0 on FROG (confirmed all-zero — Section
            # 8.6) with no special-casing needed, matching its "assume
            # static sensor" fallback exactly.
            ego_dtheta = theta - prev_theta
            ego_dxy = odom_xya_delta_to_tracker_frame(wx - prev_wx, wy - prev_wy, theta)
            prev_theta, prev_wx, prev_wy = theta, wx, wy
            for score, x, y in tracker.step(by_frame.get(frame_idx, []), ego_dtheta, ego_dxy):
                new_x.append(x); new_y.append(y); new_f.append(frame_idx)
                new_p.append([0.0, 0.0, 0.0, score])
        det_x = np.array(new_x, dtype=np.float32)
        det_y = np.array(new_y, dtype=np.float32)
        det_f = np.array(new_f, dtype=np.int64)
        det_p = np.array(new_p, dtype=np.float32) if new_p else np.zeros((0, 4), dtype=np.float32)

    wd, wc, wa, wp = _process_detections(
        det_x, det_y, det_p, det_f,
        all_wcs, all_was, all_wps, eval_r,
    )
    result = {
        "agnostic": _safe_auc(*wd[:2]),
        "wc":       _safe_auc(*wc[:2]),
        "wa":       _safe_auc(*wa[:2]),
        "wp":       _safe_auc(*wp[:2]),
    }
    if return_curves:
        # (recall, precision, threshold) arrays for the "wp" (person) class —
        # for error-breakdown analysis (TP/FP/FN at a chosen operating point)
        # rather than just the integrated AUC. See utils/error_breakdown.py.
        result["wp_curve"] = wp
    return result


# ---------------------------------------------------------------------------
# Checkpoint helpers
# ---------------------------------------------------------------------------

def _arch_metadata(net) -> dict:
    """
    Extract architecture-capacity hyperparameters directly from a model
    instance, for checkpoints saved via the generic save_checkpoint() path
    (train_model()) — which historically saved none of this — rather than
    each class's own save_weights() method (which does). Without it, a
    custom-capacity run (--channels, --n-spatial-stages, etc., e.g. the
    overfitting-reduction experiments) can't be re-evaluated later without
    shape-mismatching against _default_args()'s hardcoded sizes.
    """
    meta = {}
    for attr in ("n_time", "channels", "n_spatial_stages", "unet_channels"):
        if hasattr(net, attr):
            meta[attr] = getattr(net, attr)
    # FullScanTCNDetector doesn't keep tcn_channels/backbone_channels as
    # plain attributes — derive them the same way its own save_weights() does.
    if hasattr(net, "temporal_tcn") and hasattr(net, "backbone"):
        meta["tcn_channels"] = net.temporal_tcn[0].conv.out_channels
        meta["backbone_channels"] = net.backbone.conv4.out_channels
    return meta


def save_checkpoint(path: Path, net, optimizer, epoch: int,
                    detector_name: str, dataset_name: str):
    torch.save({
        "detector":  detector_name,
        "model":     net.state_dict(),
        "optimizer": optimizer.state_dict(),
        "epoch":     epoch,
        "dataset":   dataset_name,
        **_arch_metadata(net),
    }, path)
    print(f"  Checkpoint saved -> {path}")


def load_checkpoint(path: Path, net, optimizer=None):
    ckpt = torch.load(path, map_location="cpu")
    net.load_state_dict(ckpt["model"])
    if optimizer is not None and "optimizer" in ckpt:
        optimizer.load_state_dict(ckpt["optimizer"])
    epoch = ckpt.get("epoch", 0)
    print(f"  Loaded checkpoint from {path}  (epoch {epoch})")
    return epoch


# ---------------------------------------------------------------------------
# Defaults helper (for programmatic / notebook use)
# ---------------------------------------------------------------------------

def _default_args(**overrides) -> SimpleNamespace:
    """
    Return a SimpleNamespace with all training defaults.

    Useful for notebook cells or scripts that call train_model() directly
    without going through argparse.  Keyword arguments override defaults.

    Example
    -------
    >>> args = _default_args(detector="drspaam", epochs=20, patience=10)
    >>> history = train_model(args)

    Notes
    -----
    Both full-scan models (spacetime_cnn, fullscan_tcn) are non-recursive
    (CNN/TCN only) and DirectML-compatible; force_cpu is provided for parity
    with other backends but neither model needs it.
    """
    defaults = dict(
        detector="spacetime_cnn",
        dataset="frog",
        train_split="train",
        val_split="val",
        epochs=20,
        lr=1e-3,
        weight_decay=1e-4,
        dropout=0.5,
        time_frame=5,
        dtime=1,
        beam_shift_aug=0,
        diff_channels=False,
        global_normalize=False,
        local_normalize_window=0,
        range_jitter_scale=0.0,
        range_jitter_offset=0.0,
        vote_radius=0.6,
        vote_weight=0.02,
        subsample=1.0,
        batch_size=4,
        frame_cache=True,
        # full-scan architecture hyperparams
        backbone_channels=64,
        channels=96,
        n_spatial_stages=3,
        tcn_channels=64,
        unet_channels=32,
        # alignment
        align_scans=True,
        zero_history=False,
        # regularisation / scheduling
        patience=5,
        lr_schedule="plateau",
        # checkpoint
        out=Path("weights_trained.pth"),
        resume=None,
        weights=None,
        # detection head (full-scan models only) — resolved below, after
        # `overrides` is applied, so it can depend on the final `detector`
        heatmap_sigma=2.0,
        # evaluation
        eval_only=False,
        eval_r=0.5,
        auc_every=5,
        force_cpu=False,
    )
    defaults.update(overrides)
    if "head" not in overrides:
        # temporal_unet defaults to heatmap (matches LFE-Peaks); every other
        # full-scan model defaults to the DROW-style head. Mirrors the CLI's
        # post-parse resolution in main() — see the comment there.
        defaults["head"] = "heatmap" if defaults["detector"] == "temporal_unet" else "drow"
    return SimpleNamespace(**defaults)


# ---------------------------------------------------------------------------
# Main training routine
# ---------------------------------------------------------------------------

def train_model(args) -> dict:
    """
    Run the full training pipeline for args.epochs epochs.

    Parameters
    ----------
    args : argparse.Namespace or SimpleNamespace
        All training options.  Call _default_args(**overrides) to get a
        fully-populated namespace for programmatic use.

    Returns
    -------
    dict with keys:
        epochs            list[int]    epoch numbers recorded
        train_loss        list[float]
        train_class_loss  list[float]
        train_vote_loss   list[float]
        val_loss          list[float]  (empty when no val split)
        val_class_loss    list[float]
        val_vote_loss     list[float]
        auc_epochs        list[int]    epochs at which AUC was evaluated
        val_auc_agnostic  list[float]
        val_auc_wc        list[float]
        val_auc_wa        list[float]
        val_auc_wp        list[float]
        stopped_epoch     int          last epoch trained

    Notes
    -----
    Early stopping
        Requires a val split (--val-split / args.val_split).  When patience>0
        and val_loss does not improve for <patience> epochs, training stops and
        the best checkpoint is loaded before saving the final weights.
        Best checkpoint is written to <out>.best.pth.

    LR scheduling
        "cosine"  — CosineAnnealingLR over args.epochs, eta_min = lr/100
        "plateau" — ReduceLROnPlateau on val_loss (requires val split)
        "none"    — constant learning rate
    """
    # Device
    force_cpu = getattr(args, "force_cpu", False)
    if force_cpu:
        device, using_dml = "cpu", False
        print("  [INFO] force_cpu=True — using CPU regardless of GPU availability.\n")
    else:
        device, using_dml = detect_device()
        if using_dml:
            print("  Note: DirectML — tensors moved to DML device via .to().\n")
        else:
            print(f"  Device: {device}\n")

    train_ds, val_ds, cfg = _setup_datasets(args)

    net = _build_model(args).to(device)
    if getattr(args, "init_weights", None):
        load_checkpoint(args.init_weights, net)   # weights only — fresh optimizer/epoch
    if getattr(args, "freeze_backbone", False):
        _freeze_backbone(net)
    optimizer = _make_optimizer(
        (p for p in net.parameters() if p.requires_grad),
        lr=args.lr, weight_decay=args.weight_decay, using_dml=using_dml)

    start_epoch = 0
    if args.resume:
        start_epoch = load_checkpoint(args.resume, net, optimizer)

    # Build frame datasets once.  By default preprocessing is cached and
    # amortised across epochs; pass --no-frame-cache to trade that RAM
    # (~2.6 GB for FROG's full train split in raw_scan mode) back for
    # recomputing preprocessing on every access instead.
    _input_mode     = getattr(net, "INPUT_MODE", "cutout")
    _nsamp          = getattr(net, "N_SAMP", DrowDetector.N_SAMP)
    _frame_cache    = getattr(args, "frame_cache", True)
    _head           = getattr(args, "head",
                              "heatmap" if args.detector == "temporal_unet" else "drow")
    _heatmap_sigma  = getattr(args, "heatmap_sigma", 2.0)
    _align_scans    = getattr(args, "align_scans", True)
    _zero_history   = getattr(args, "zero_history", False)
    _dtime          = getattr(args, "dtime", 1)
    _beam_shift_aug = getattr(args, "beam_shift_aug", 0)
    _diff_channels  = getattr(args, "diff_channels", False)
    _global_normalize = getattr(args, "global_normalize", False)
    _local_normalize_window = getattr(args, "local_normalize_window", 0)
    _range_jitter_scale  = getattr(args, "range_jitter_scale", 0.0)
    _range_jitter_offset = getattr(args, "range_jitter_offset", 0.0)
    train_frame_ds = LidarFrameDataset(
        train_ds, cfg, _input_mode, args.vote_radius, _nsamp,
        cache=_frame_cache, head=_head, heatmap_sigma=_heatmap_sigma,
        align_scans=_align_scans, zero_history=_zero_history, dtime=_dtime,
        beam_shift_aug=_beam_shift_aug, diff_channels=_diff_channels,
        global_normalize=_global_normalize,
        local_normalize_window=_local_normalize_window,
        range_jitter_scale=_range_jitter_scale,
        range_jitter_offset=_range_jitter_offset)
    val_frame_ds = (LidarFrameDataset(
        val_ds, cfg, _input_mode, args.vote_radius, _nsamp,
        cache=_frame_cache, head=_head, heatmap_sigma=_heatmap_sigma,
        align_scans=_align_scans, zero_history=_zero_history, dtime=_dtime,
        beam_shift_aug=0,  # never augment validation
        diff_channels=_diff_channels, global_normalize=_global_normalize,
        local_normalize_window=_local_normalize_window,
        range_jitter_scale=0.0, range_jitter_offset=0.0)  # never augment validation
        # the three representation flags above must match train
        if val_ds is not None else None)

    n_params = sum(p.numel() for p in net.parameters())
    print(f"Model: {args.detector}  —  {n_params:,} parameters\n")

    # LR scheduler
    schedule = getattr(args, "lr_schedule", "none")
    if schedule == "cosine":
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            optimizer, T_max=args.epochs, eta_min=args.lr * 1e-2)
    elif schedule == "plateau":
        if val_ds is None:
            print("  [WARN] lr_schedule=plateau requires a val split; "
                  "scheduler disabled.\n")
            scheduler = None
        else:
            scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
                optimizer, patience=max(3, args.epochs // 10),
                factor=0.5)
    else:
        scheduler = None

    # Early stopping
    patience = getattr(args, "patience", 0)
    if patience > 0 and val_ds is None:
        print("  [WARN] patience>0 requires a val split; early stopping disabled.\n")
        patience = 0

    best_val_loss    = float("inf")
    patience_counter = 0
    best_path = args.out.with_suffix(".best.pth") if patience > 0 else None

    history = dict(
        epochs=[],
        train_loss=[], train_class_loss=[], train_vote_loss=[],
        val_loss=[], val_class_loss=[], val_vote_loss=[],
        auc_epochs=[],
        val_auc_agnostic=[], val_auc_wc=[], val_auc_wa=[], val_auc_wp=[],
        stopped_epoch=start_epoch,
    )

    print(f"Training {args.detector} for {args.epochs} epoch(s), "
          f"subsample={args.subsample:.0%} …\n")

    epoch_bar = tqdm(range(start_epoch + 1, start_epoch + args.epochs + 1),
                     desc="Epochs", unit="ep", dynamic_ncols=True)

    final_epoch = start_epoch
    for epoch in epoch_bar:
        tl, tc, tv = train_epoch(
            net, train_frame_ds, optimizer,
            vote_weight=args.vote_weight,
            subsample=args.subsample, device=device, batch_size=args.batch_size,
        )
        history["epochs"].append(epoch)
        history["train_loss"].append(tl)
        history["train_class_loss"].append(tc)
        history["train_vote_loss"].append(tv)

        msg = (f"Epoch {epoch:3d}/{start_epoch + args.epochs}  "
               f"train_loss={tl:.4f}  (class={tc:.4f}, vote={tv:.4f})")

        stop = False
        if val_ds is not None:
            vl, vc, vv = evaluate_loss(
                net, val_frame_ds,
                vote_weight=args.vote_weight,
                subsample=args.subsample, device=device,
                batch_size=args.batch_size,
            )
            history["val_loss"].append(vl)
            history["val_class_loss"].append(vc)
            history["val_vote_loss"].append(vv)
            msg += f"  |  val_loss={vl:.4f}  (class={vc:.4f}, vote={vv:.4f})"

            if isinstance(scheduler, torch.optim.lr_scheduler.ReduceLROnPlateau):
                scheduler.step(vl)

            # Early stopping
            if patience > 0:
                if vl < best_val_loss:
                    best_val_loss = vl
                    patience_counter = 0
                    save_checkpoint(best_path, net, optimizer, epoch,
                                    args.detector, cfg.name)
                else:
                    patience_counter += 1
                    msg += f"  patience={patience_counter}/{patience}"
                    if patience_counter >= patience:
                        tqdm.write(msg)
                        tqdm.write(
                            f"  Early stopping at epoch {epoch} "
                            f"(no val improvement for {patience} epochs)."
                        )
                        final_epoch = epoch
                        stop = True

        if scheduler is not None and not isinstance(
                scheduler, torch.optim.lr_scheduler.ReduceLROnPlateau):
            scheduler.step()

        tqdm.write(msg)

        # AUC evaluation
        auc_every = getattr(args, "auc_every", 0)
        if auc_every > 0 and epoch % auc_every == 0:
            auc_ds = val_ds or train_ds
            aucs = evaluate_auc(net, auc_ds, cfg, eval_r=args.eval_r,
                                device=device, batch_size=args.batch_size,
                                align_scans=_align_scans, zero_history=_zero_history,
                                diff_channels=_diff_channels,
                                global_normalize=_global_normalize,
                                local_normalize_window=_local_normalize_window)
            history["auc_epochs"].append(epoch)
            history["val_auc_agnostic"].append(aucs["agnostic"])
            history["val_auc_wc"].append(aucs["wc"])
            history["val_auc_wa"].append(aucs["wa"])
            history["val_auc_wp"].append(aucs["wp"])
            tqdm.write(f"  AUC  agnostic={aucs['agnostic']:.1%}  "
                       f"wc={aucs['wc']:.1%}  wa={aucs['wa']:.1%}  "
                       f"wp={aucs['wp']:.1%}")

        final_epoch = epoch
        if stop:
            epoch_bar.close()
            break

    history["stopped_epoch"] = final_epoch

    # Final AUC (skip if already computed for this epoch)
    print()
    if val_ds is not None:
        last_auc_epoch = history["auc_epochs"][-1] if history["auc_epochs"] else -1
        if last_auc_epoch != final_epoch:
            print("Computing final AUC on val set …")
            aucs = evaluate_auc(net, val_ds, cfg, eval_r=args.eval_r,
                                device=device, batch_size=args.batch_size,
                                align_scans=_align_scans, diff_channels=_diff_channels,
                                global_normalize=_global_normalize,
                                local_normalize_window=_local_normalize_window)
            history["auc_epochs"].append(final_epoch)
            history["val_auc_agnostic"].append(aucs["agnostic"])
            history["val_auc_wc"].append(aucs["wc"])
            history["val_auc_wa"].append(aucs["wa"])
            history["val_auc_wp"].append(aucs["wp"])
            print(f"  Agnostic (any) : {aucs['agnostic']:.1%}")
            print(f"  Wheelchair(wc) : {aucs['wc']:.1%}")
            print(f"  Walker    (wa) : {aucs['wa']:.1%}")
            print(f"  Person    (wp) : {aucs['wp']:.1%}")
            print()

    # Load best weights before saving final checkpoint
    if best_path is not None and best_path.exists():
        print(f"  Loading best checkpoint (val_loss={best_val_loss:.4f}) …")
        load_checkpoint(best_path, net)

    save_checkpoint(args.out, net, optimizer, epoch=final_epoch,
                    detector_name=args.detector, dataset_name=cfg.name)

    return history


# ---------------------------------------------------------------------------
# Hyperparameter tuning (Optuna)
# ---------------------------------------------------------------------------

def tune_model(args) -> dict:
    """
    Run an Optuna study to find the best hyperparameters for args.detector.

    Parameters
    ----------
    args : Namespace
        Base training args.  ``args.tune_trials`` and ``args.tune_epochs``
        control the study; all other args serve as defaults that are partially
        overridden inside each trial.

    Returns
    -------
    dict  Best hyperparameters found by Optuna.

    Notes
    -----
    Objective  — minimise the lowest val_loss reached in the trial.
                 Falls back to train_loss when no val split is available.
    Parameters tuned for every model:
        lr, weight_decay, dropout
    Additional parameters for full-scan models:
        backbone_channels                  (fullscan_tcn)
        channels, n_spatial_stages         (spacetime_cnn)
        tcn_channels                       (fullscan_tcn only)
    """
    try:
        import optuna
    except ImportError:
        raise ImportError(
            "optuna is required for hyperparameter tuning.  "
            "Install it with: pip install optuna"
        )

    import tempfile

    optuna.logging.set_verbosity(optuna.logging.WARNING)

    det          = args.detector
    tune_epochs  = getattr(args, "tune_epochs",  10)
    tune_trials  = getattr(args, "tune_trials",  30)

    def objective(trial: "optuna.Trial") -> float:
        # Copy base args, then override with trial suggestions
        t = SimpleNamespace(**vars(args))
        t.lr           = trial.suggest_float("lr",           1e-5, 1e-2, log=True)
        t.weight_decay = trial.suggest_float("weight_decay", 1e-6, 1e-2, log=True)
        t.dropout      = trial.suggest_float("dropout",      0.0,  0.6,  step=0.1)

        if det == "fullscan_tcn":
            t.backbone_channels = trial.suggest_categorical(
                "backbone_channels", [32, 64, 128])
            t.tcn_channels = trial.suggest_categorical("tcn_channels", [32, 64, 128])
        if det == "spacetime_cnn":
            t.channels         = trial.suggest_categorical("channels", [72, 96, 120])
            t.n_spatial_stages = trial.suggest_int("n_spatial_stages", 2, 4)
        if det == "temporal_unet":
            t.unet_channels = trial.suggest_categorical("unet_channels", [16, 24, 32, 48])

        # Shorter run; skip AUC inside trials (expensive)
        t.epochs    = tune_epochs
        t.auc_every = 0
        t.patience  = max(3, tune_epochs // 3)

        # Temporary checkpoint files — cleaned up after the trial
        tmp = Path(tempfile.mktemp(suffix=".pth"))
        t.out = tmp

        try:
            history = train_model(t)
        finally:
            tmp.unlink(missing_ok=True)
            tmp.with_suffix(".best.pth").unlink(missing_ok=True)

        if history["val_loss"]:
            return min(history["val_loss"])
        return min(history["train_loss"])

    study = optuna.create_study(
        direction="minimize",
        study_name=f"tune_{det}",
        sampler=optuna.samplers.TPESampler(seed=42),
    )
    print(f"\nStarting Optuna study: {tune_trials} trials × {tune_epochs} epochs "
          f"each for '{det}' …\n")
    study.optimize(objective, n_trials=tune_trials, show_progress_bar=True)

    best = study.best_params
    print(f"\n{'='*60}")
    print(f"  Best val_loss : {study.best_value:.4f}")
    print(f"  Best params   :")
    for k, v in best.items():
        print(f"    {k} = {v}")
    print(f"{'='*60}\n")

    return best


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Train and evaluate person detectors on DROW or FROG.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    # Trainable detectors — DROW/DR-SPAAM use published weights, LFE detectors are ONNX-only
    _TRAINABLE = [
        "algorithmic",
        "li2former",
        "spacetime_cnn", "fullscan_tcn", "temporal_unet",
    ]
    parser.add_argument(
        "--detector",
        choices=_TRAINABLE,
        default="spacetime_cnn",
        help="Detector to train/evaluate (default: spacetime_cnn)",
    )
    # Dataset
    parser.add_argument("--dataset",     choices=["drow", "frog", "jrdb"], default="frog")
    parser.add_argument("--train-split", default="train",
                        help="Training split (default: train)")
    parser.add_argument("--val-split",   default="val",
                        help="Validation split (default: val; '' to disable)")
    # Training
    parser.add_argument("--epochs",      type=int,   default=10)
    parser.add_argument("--lr",          type=float, default=1e-3)
    parser.add_argument("--weight-decay",type=float, default=1e-4)
    parser.add_argument("--dropout",     type=float, default=0.5,
                        help="Dropout for all models (default: 0.5)")
    parser.add_argument("--time-frame",  type=int,   default=5,
                        help="Number of scans in the temporal window (default: 5)")
    parser.add_argument("--dtime",       type=int,   default=1,
                        help="Stride (in raw scans) between the --time-frame scans "
                             "fetched per sample (default: 1 = consecutive frames). "
                             "E.g. on FROG (40Hz), --time-frame 10 --dtime 20 spans "
                             "the last ~4.5s at 500ms spacing instead of the default "
                             "~125ms window. See DROW_Dataset/FROG_Dataset.get_scan().")
    parser.add_argument("--beam-shift-aug", type=int, default=0,
                        help="Training-only data augmentation: max random beam-index "
                             "roll applied per training sample (default: 0 = off). "
                             "See LidarFrameDataset's beam_shift_aug docstring.")
    parser.add_argument("--diff-channels", action="store_true", default=False,
                        help="raw_scan mode only: replace T-1 of the T temporal "
                             "slots with frame-to-frame differences (current frame "
                             "kept raw) -- see _diff_encode(). A representation "
                             "choice, not an augmentation: applied identically at "
                             "train and eval time (evaluate.py --eval-diff-channels "
                             "must match).")
    parser.add_argument("--global-normalize", action="store_true", default=False,
                        help="raw_scan mode only: subtract the current frame's mean "
                             "range from every beam of every temporal slice -- see "
                             "_global_normalize(). A representation choice, not an "
                             "augmentation: applied identically at train and eval "
                             "time (evaluate.py --eval-global-normalize must match).")
    parser.add_argument("--local-normalize-window", type=int, default=0,
                        help="raw_scan mode only: subtract a local beam-neighbourhood "
                             "moving-average (window size in beams, 0 = off) from "
                             "every beam of every temporal slice -- see "
                             "_local_normalize(). The DR-SPAAM-inspired per-beam "
                             "centering idea, without DR-SPAAM's expensive per-beam "
                             "architecture. A representation choice, not an "
                             "augmentation: applied identically at train and eval "
                             "time (evaluate.py --eval-local-normalize-window must "
                             "match).")
    parser.add_argument("--range-jitter-scale", type=float, default=0.0,
                        help="Training-only augmentation: multiplicative range jitter, "
                             "fraction (0 = off, e.g. 0.1 = *[0.9, 1.1] per sample). "
                             "See _jitter_range(). Applied to x only, never at eval.")
    parser.add_argument("--range-jitter-offset", type=float, default=0.0,
                        help="Training-only augmentation: additive range jitter in "
                             "metres (0 = off, e.g. 0.1 = +[-0.1, 0.1]m per sample). "
                             "See _jitter_range(). Applied to x only, never at eval.")
    parser.add_argument("--vote-radius", type=float, default=0.6)
    parser.add_argument("--vote-weight", type=float, default=0.02)
    parser.add_argument("--subsample",   type=float, default=1.0,
                        help="Fraction of frames per epoch (use 0.05 for quick dev)")
    parser.add_argument("--batch-size",  type=int,   default=4,
                        help="Frames per optimizer step; effective beam batch = "
                             "batch_size × N_beams (default: 4)")
    parser.add_argument("--no-frame-cache", dest="frame_cache",
                        action="store_false",
                        help="Recompute frame preprocessing on every access instead "
                             "of caching it in RAM across epochs. Trades training "
                             "time for memory (~2.6 GB for FROG's full train split "
                             "in raw_scan mode) — use on RAM-constrained machines.")
    # Architecture hyperparams (full-scan models only)
    parser.add_argument("--backbone-channels", type=int, default=64,
                        help="Conv channels in DilatedScanBackbone "
                             "(FullScanTCN; default: 64)")
    parser.add_argument("--channels",        type=int, default=96,
                        help="Internal channel width (SpaceTimeCNN; default: 96, "
                             "must be divisible by 3×8=24 for GroupNorm)")
    parser.add_argument("--n-spatial-stages", type=int, default=3,
                        help="Spatial inception stages 1–4 (SpaceTimeCNN; default: 3). "
                             "Beam RF: 3→17, 4→49, 5→177, 6→689 beams.")
    parser.add_argument("--tcn-channels", type=int, default=64,
                        help="Temporal TCN channel width (FullScanTCN; default: 64)")
    parser.add_argument("--unet-channels", type=int, default=32,
                        help="Base encoder channel width (TemporalUNet; default: 32). "
                             "Doubles at each encoder stage: 32→64→128→256.")
    # Odometry alignment
    parser.add_argument("--align-scans", dest="align_scans", action="store_true",
                        default=True,
                        help="Apply rotation-only odometry alignment to the T-frame "
                             "raw scan window (default: on). Uses aligned_raw_scan(); "
                             "gracefully degrades to raw_scan() when odom is absent.")
    parser.add_argument("--no-align-scans", dest="align_scans", action="store_false",
                        help="Disable odometry alignment (use raw, unaligned scans). "
                             "Reproduces the original unaligned baseline.")
    parser.add_argument("--zero-history", action="store_true", default=False,
                        help="Ablation: zero every historical frame in the T-frame "
                             "window (all but the current/last one) before feature "
                             "extraction, for both training and evaluation. Measures "
                             "how much the temporal window actually contributes vs. "
                             "a single-frame-equivalent input, architecture unchanged.")
    # Detection head (full-scan models only)
    parser.add_argument("--head", choices=["drow", "heatmap"], default=None,
                        help="Detection head for full-scan models (default: 'drow' "
                             "for spacetime_cnn/fullscan_tcn, 'heatmap' for "
                             "temporal_unet — resolved after parsing if omitted). "
                             "'drow': 4-class logits + vote-offset regression, same "
                             "head as DROW/DR-SPAAM — enables direct comparison. "
                             "'heatmap': 1D Gaussian heatmap + BCE loss + peak "
                             "detection decoding — simpler supervision, no vote "
                             "accumulation. Use --heatmap-sigma to control peak width.")
    parser.add_argument("--heatmap-sigma", type=float, default=2.0,
                        help="Gaussian sigma in beam units for heatmap targets "
                             "(default: 2 → ≈1° FWHM at 0.5°/beam). "
                             "Ignored when --head drow.")
    # Regularisation / scheduling
    parser.add_argument("--patience",    type=int,   default=0,
                        help="Early-stopping patience in epochs (0=disabled). "
                             "Saves best checkpoint to <out>.best.pth.")
    parser.add_argument("--lr-schedule", choices=["none", "cosine", "plateau"],
                        default="none",
                        help="LR schedule: none | cosine | plateau (default: none)")
    # Checkpointing
    parser.add_argument("--out",    type=Path, default=Path("weights_trained.pth"))
    parser.add_argument("--resume", type=Path, default=None,
                        help="Resume from checkpoint")
    parser.add_argument("--init-weights", type=Path, default=None,
                        help="Initialise model weights from a checkpoint (e.g. a "
                             "FROG-trained model) without touching optimizer state "
                             "or epoch numbering — for fine-tuning on a new dataset "
                             "with a fresh optimizer/LR, unlike --resume.")
    parser.add_argument("--freeze-backbone", action="store_true", default=False,
                        help="With --init-weights: freeze every parameter except the "
                             "final output head, so fine-tuning only re-fits the last "
                             "layer(s) instead of the whole network -- see "
                             "_freeze_backbone().")
    parser.add_argument("--weights",type=Path, default=None,
                        help="Load weights (eval-only mode)")
    # Evaluation
    parser.add_argument("--eval-only",  action="store_true")
    parser.add_argument("--eval-r",     type=float, default=0.5)
    parser.add_argument("--auc-every",  type=int,   default=0,
                        help="Compute full AUC every N epochs (0 = end only)")
    # Hyperparameter tuning (Optuna)
    parser.add_argument("--tune",        action="store_true",
                        help="Run Optuna hyperparameter search instead of training. "
                             "Requires: pip install optuna")
    parser.add_argument("--tune-trials", type=int, default=30,
                        help="Number of Optuna trials (default: 30)")
    parser.add_argument("--tune-epochs", type=int, default=10,
                        help="Epochs per trial — keep short (default: 10)")
    args = parser.parse_args()
    args.val_split = args.val_split.strip() or None
    if args.head is None:
        # temporal_unet defaults to heatmap (matches LFE-Peaks); every other
        # full-scan model defaults to the DROW-style head for a head-neutral
        # comparison. Only resolved here if the user didn't pass --head
        # explicitly (an explicit choice, e.g. --head drow on temporal_unet
        # for the ablation in docs/RESEARCH.md §5.5, is always respected).
        args.head = "heatmap" if args.detector == "temporal_unet" else "drow"

    # ------------------------------------------------------------------
    # AlgorithmicDetector: eval-only (not an nn.Module)
    # ------------------------------------------------------------------
    if args.detector == "algorithmic":
        print("AlgorithmicDetector is not trainable — running eval only.")
        dataset, cfg = _setup_datasets(SimpleNamespace(
            dataset=args.dataset,
            train_split=args.train_split,
            val_split=None,
        ))[:2]
        # Algorithmic detector does not produce logits/votes; skip AUC pipeline.
        print("(Algorithmic evaluation is available via evaluate.py --algo)")
        return

    # ------------------------------------------------------------------
    # Eval-only mode
    # ------------------------------------------------------------------
    if args.eval_only:
        device, using_dml = detect_device()
        train_ds, val_ds, cfg = _setup_datasets(args)
        net = _build_model(args).to(device)
        if args.weights:
            load_checkpoint(args.weights, net)
        elif args.resume:
            load_checkpoint(args.resume, net)
        eval_ds = val_ds or train_ds
        print("=== Evaluation ===")
        aucs = evaluate_auc(net, eval_ds, cfg, eval_r=args.eval_r, device=device,
                            batch_size=args.batch_size,
                            align_scans=getattr(args, "align_scans", True),
                            diff_channels=getattr(args, "diff_channels", False),
                            global_normalize=getattr(args, "global_normalize", False),
                            local_normalize_window=getattr(args, "local_normalize_window", 0))
        print(f"  Agnostic (any) : {aucs['agnostic']:.1%}")
        print(f"  Wheelchair(wc) : {aucs['wc']:.1%}")
        print(f"  Walker    (wa) : {aucs['wa']:.1%}")
        print(f"  Person    (wp) : {aucs['wp']:.1%}")
        return

    # ------------------------------------------------------------------
    # Hyperparameter tuning
    # ------------------------------------------------------------------
    if args.tune:
        tune_model(args)
        return

    # ------------------------------------------------------------------
    # Training
    # ------------------------------------------------------------------
    # force_cpu is not a CLI flag — it's only used programmatically.
    # Attach the default so train_model() doesn't choke on getattr.
    args.force_cpu = False
    train_model(args)


if __name__ == "__main__":
    main()
